import customtkinter as ctk
import tkinter.messagebox as messagebox
import random


def conversational_bot(main_content_frame):
    # Clear the main content frame
    for widget in main_content_frame.winfo_children():
        widget.destroy()

    # Header
    header_label = ctk.CTkLabel(main_content_frame, text="Conversational Bot", font=("Arial", 24, "bold"))
    header_label.pack(pady=10)

    bot_label = ctk.CTkLabel(main_content_frame, text="Chat with the bot about your feelings:", font=("Arial", 16))
    bot_label.pack(pady=10)

    # Entry for user input
    bot_input = ctk.CTkEntry(main_content_frame, placeholder_text="Enter your feelings here")
    bot_input.pack(pady=10, fill="x", padx=50)

    # Frame for displaying conversation
    chat_frame = ctk.CTkFrame(main_content_frame, fg_color="white", height=400, width=600)
    chat_frame.pack(fill="both", expand=True, pady=10, padx=10)

    chat_textbox = ctk.CTkTextbox(chat_frame, state="disabled", wrap="word", width=600)
    chat_textbox.pack(fill="both", expand=True)

    # Generate responses for moods
    bot_responses = {
        "Happy": [
            "That's wonderful! What's making your day so great?", 
            "Keep shining—your happiness is contagious!", 
            "It's amazing to hear you're feeling good! Want to share the joy?", 
            "What's the highlight of your day so far?", 
            "Your happiness makes this interaction better!",
            "Spread that positivity around—it's powerful!",
            "You seem to be in high spirits. Any exciting plans?",
            "It's always refreshing to see someone so cheerful!",
            "Happiness looks good on you!",
            "Tell me, what's making you smile today?",
            "That's fantastic! Anything exciting happening?",
            "I love your energy—keep it up!",
            "You're glowing with happiness. What's the secret?",
            "Let's keep this positivity going. How's everything else?",
            "Being happy suits you. What's the source of your joy?",
            "Your good vibes are uplifting—thank you!",
            "What's one thing that made you smile today?",
            "So great to hear you're doing well!",
            "Your happiness is inspiring! Keep it up!",
            "Feeling this good is a gift—what's the occasion?",
            "I'm so glad you're feeling this way!",
            "Bright days are the best days, aren't they?",
            "Your cheerfulness brightens the moment!",
            "Keep that smile alive—it's beautiful!",
            "Tell me something fun about your day.",
            "Happiness is meant to be shared—thanks for sharing yours!",
            "I'm thrilled to hear you're feeling so positive!",
            "What's one thing that always lifts your spirits?",
            "Your good mood is a reminder to enjoy the little things!",
            "Keep spreading those good vibes—everyone needs it!",
        ],
        "Calm": [
            "It's great to hear you're at peace.", 
            "Calmness is a superpower—how do you maintain it?", 
            "Quiet moments can be so refreshing. Enjoy it!", 
            "What's contributing to your peace of mind today?", 
            "Your calm energy is grounding—thank you.",
            "Anything on your mind, or just enjoying the stillness?",
            "This sense of calm is contagious—share your secret!",
            "Take a deep breath and savor this peace.",
            "Moments like these are so important. Hold on to it.",
            "How do you usually keep yourself this relaxed?",
            "I'm glad to hear you're feeling centered.",
            "Stillness is a beautiful state of mind.",
            "You sound so at ease. Is there anything I can do for you?",
            "It's wonderful to be in this calm space with you.",
            "The world could use more calm energy like yours.",
            "Feeling grounded is such a blessing, isn't it?",
            "How do you usually unwind to feel this way?",
            "Peace is precious—enjoy it fully.",
            "It's great to hear you're in a good headspace.",
            "Do you have any rituals that help you stay calm?",
            "Your tranquility is inspiring.",
            "It's nice to take a breather and just be, isn't it?",
            "Savor this sense of serenity—it's invaluable.",
            "What's been keeping you so relaxed lately?",
            "Feeling calm is such a gift—enjoy it!",
            "How do you stay so centered? Share your tips!",
            "It's refreshing to hear such peaceful vibes from you.",
            "Moments like these are what we live for.",
            "Your calmness feels so grounding—thank you for sharing.",
            "Enjoy this peace—it's well deserved!",
        ],
        "Confident": [
            "Your confidence shines through—keep it up!", 
            "You sound unstoppable today!", 
            "Confidence looks good on you. What's the reason?", 
            "Let's make the most of this confident energy!", 
            "You're radiating self-assurance—what's the secret?",
            "It's great to see you feeling so sure of yourself!",
            "Tell me, what's making you feel so empowered today?",
            "Confidence can take you far—where's it taking you next?",
            "I can tell you're ready to conquer anything!",
            "Your self-belief is inspiring—never lose it!",
            "What's the source of this confidence today?",
            "Keep that confidence high—it's magnetic!",
            "You're oozing determination. What's the next move?",
            "With this energy, you can achieve anything!",
            "What's fueling your self-assurance right now?",
            "I love seeing you this empowered!",
            "Your confidence is inspiring—others will notice it too!",
            "You've got this energy about you—what's the goal?",
            "Your assurance is contagious—let's make great things happen!",
            "It's amazing to hear how grounded you feel.",
            "You sound ready to tackle any challenge—what's next?",
            "This confidence is your superpower!",
            "Keep channeling this energy—it'll take you far.",
            "What are you most proud of today?",
            "Let's channel that confidence into something amazing.",
            "You're a force to be reckoned with—keep it up!",
            "You've got everything it takes. Go for it!",
            "Tell me more about what's boosting your confidence.",
            "You're setting a powerful example!",
            "This level of confidence is inspiring—stay bold!",
        ],
        "Inspired": [
            "That spark of inspiration is amazing—what's your next idea?",
            "What's fueling your creativity today?",
            "I can tell you're ready to achieve something great!",
            "What's the big idea? I'd love to hear about it.",
            "Your inspiration is contagious. Keep going!",
            "Let's turn your ideas into reality—what's your plan?",
            "What's motivating you right now?",
            "Inspired moments like these are powerful—how can I help?",
            "What's your vision? Let's make it happen!",
            "You're onto something great—tell me more!",
            "What's been sparking your creativity lately?",
            "Feeling inspired is the first step toward greatness!",
            "What's the project or idea that has you fired up?",
            "Your energy is inspiring—how can I support you?",
            "What's one thing you want to create today?",
            "You're brimming with potential—what's the focus?",
            "Let's harness this inspiration. What's next?",
            "Tell me about your ideas—I'm all ears!",
            "Your creativity is shining through—keep at it!",
            "What's been inspiring you lately?",
            "I love this energy—how can we channel it?",
            "What's your next big move? Let's make it happen!",
            "Your drive is amazing. Let's build on it!",
            "What's something you've been wanting to create or achieve?",
            "This is a great moment to dream big—what's your goal?",
            "Feeling inspired is a gift—what will you do with it?",
            "What's your creative process like right now?",
            "Your inspiration is the spark for something amazing!",
            "What's pushing you forward today?",
            "Keep chasing your ideas—they're worth it!",
        ],
        "Sad": [
            "I'm here for you. Want to talk about what's on your mind?",
            "It's okay to feel sad. Let's work through it together.",
            "Sometimes a good cry can help—how can I support you?",
            "I'm sorry you're feeling this way. What's going on?",
            "Would it help to talk about what's making you sad?",
            "You're not alone—I'm here for you.",
            "It's okay to not be okay. Take your time.",
            "Let's figure this out together. What's troubling you?",
            "Sadness can be overwhelming, but you don't have to face it alone.",
            "I care about how you're feeling—share if you'd like.",
            "Do you want to talk about it, or just sit quietly for a bit?",
            "I'm listening. What's weighing on your heart?",
            "You matter, and your feelings matter too.",
            "It's okay to let your emotions out. I'm here to help.",
            "What's been on your mind lately?",
            "Sometimes sadness passes like a storm—let's weather it together.",
            "You're stronger than you feel right now.",
            "Would you like some suggestions to feel better?",
            "You're not alone in this—I've got your back.",
            "What's one small thing we can do to lighten the load?",
            "It's okay to feel this way. Let's take it one step at a time.",
            "I'm sorry you're hurting. How can I help?",
            "Let's focus on one thing that might bring you comfort.",
            "Take a deep breath. You're doing your best.",
            "Want to share more about what's causing these feelings?",
            "It's okay to not have all the answers right now.",
            "I'm here to listen whenever you're ready.",
            "You've been through tough times before—you can handle this.",
            "Would a distraction or a comforting activity help?",
            "You're not alone in this. I'm right here with you.",
        ],
        "Fear": [
            "It's okay to feel afraid. What's causing it?",
            "You're safe here—want to talk about it?",
            "Take a deep breath. You've got this.",
            "What's making you feel this way? Let's tackle it together.",
            "Fear is a natural response. Let's work through it.",
            "You're stronger than you think—let's face this.",
            "I'm here to help you feel safe and supported.",
            "What can we do to ease your fear?",
            "It's okay to feel scared. Let's take small steps forward.",
            "Would it help to talk about what's worrying you?",
            "You're not alone in this—I'm here for you.",
            "What's the first thing we can do to make you feel better?",
            "Sometimes naming the fear can make it smaller.",
            "You're in control, even if it doesn't feel like it.",
            "What's one thing that could bring you comfort right now?",
            "You're brave for facing this feeling.",
            "Fear can feel overwhelming, but it won't last forever.",
            "What's the worst-case scenario? Let's tackle it.",
            "I believe in your ability to handle this.",
            "You're stronger than this fear—let's prove it.",
            "Let's focus on what you can control right now.",
            "What's one small action we can take to feel safer?",
            "I'm proud of you for facing your fears.",
            "Fear often signals growth—what might you learn from this?",
            "You're not alone in feeling this way.",
            "What's the story your fear is telling? Let's rewrite it.",
            "You're safe. Let's take things one step at a time.",
            "Even in fear, you have courage—hold on to that.",
            "Would grounding techniques help? Let's try them.",
            "Fear passes, but your strength remains.",
        ],
        "Anger": [
            "It's okay to feel angry—what's making you feel this way?",
            "Your feelings are valid. Let's talk about it.",
            "Anger can be overwhelming—how can I help?",
            "I'm here to listen. Want to share what's on your mind?",
            "Let's work through this together—what's frustrating you?",
            "Anger often points to something deeper. What's underneath it?",
            "Take a deep breath. Let's figure this out.",
            "It's okay to express your anger. I'm here to support you.",
            "What's one thing we can do to ease your frustration?",
            "You're not alone in feeling this way.",
            "Would it help to talk through what's upsetting you?",
            "Anger is a natural reaction—how can we channel it?",
            "What's the root cause of your anger right now?",
            "Let's focus on what's within your control.",
            "Sometimes expressing your anger can help. Want to vent?",
            "It's okay to feel this way. Let's take it step by step.",
            "What's been building up for you? Let's unpack it.",
            "Even in anger, you have the strength to stay calm.",
            "Would taking a break or a walk help you feel better?",
            "Your emotions matter—let's process them together.",
            "What's the first thing that comes to mind when you think about this anger?",
            "Anger can be a sign of something needing attention. What is it?",
            "Let's find a way to channel this into something constructive.",
            "You're allowed to feel upset. Let's talk about it.",
            "Would some deep breathing or grounding techniques help right now?",
            "What's one small action you can take to feel more in control?",
            "Even strong emotions like anger can teach us something. What's it saying?",
            "How can I support you through this moment?",
            "You don't have to face this alone. Let's handle it together.",
            "What's one thing that might bring you a bit of peace right now?",
        ],
        "Shame": [
            "I'm here for you. Want to talk about what's on your mind?",
            "It's okay to feel this way. You're not alone.",
            "You're more than your mistakes—let's talk about it.",
            "What's making you feel this way? I'm here to listen.",
            "Sometimes shame feels heavy, but it doesn't define you.",
            "Your worth is not tied to this moment—remember that.",
            "Let's explore what's behind this feeling of shame.",
            "You're not alone in feeling this way. I'm here for you.",
            "What happened doesn't change your value as a person.",
            "It's okay to make mistakes. What matters is what you learn from them.",
            "Would it help to talk about what's making you feel this way?",
            "Be kind to yourself—you deserve compassion.",
            "What's one thing you can do to start forgiving yourself?",
            "Shame can be isolating, but you're not alone.",
            "Let's focus on moving forward together.",
            "You're not defined by this one moment or action.",
            "It's okay to feel this way. Let's work through it.",
            "You're worthy of understanding and support.",
            "What's the story you're telling yourself? Let's challenge it.",
            "It's brave to face these feelings. I'm proud of you.",
            "What's one small thing you can do to be kind to yourself today?",
            "Shame is a heavy emotion—let's lighten the load together.",
            "You're more than your struggles. Let's move forward.",
            "Even when you feel this way, you deserve care and understanding.",
            "What's one step toward letting go of this feeling?",
            "You're not alone in this—I'm here to help.",
            "Let's reframe this experience together.",
            "You're stronger than this feeling of shame.",
            "What's one thing you can learn or take away from this?",
            "Your past doesn't define your future. Let's focus on what's next.",
        ],
        "Disgusted": [
            "What's making you feel this way? I'm here to listen.",
            "Disgust is a strong emotion—let's unpack it together.",
            "It's okay to feel this way. Want to talk about it?",
            "Sometimes disgust signals something deeper. What's going on?",
            "Let's focus on what's bothering you and find a way forward.",
            "I'm here to support you through this moment.",
            "What triggered this feeling? Let's work through it.",
            "Even strong emotions like disgust are valid. Let's process it.",
            "It's okay to feel this way—how can I help?",
            "What's one thing we can do to ease this feeling?",
            "Sometimes talking about it can help. Want to share more?",
            "Let's take a moment to breathe and reset.",
            "Disgust can feel overwhelming—what's the root cause?",
            "You're not alone in feeling this way. Let's handle it together.",
            "Would it help to talk about what's triggering this reaction?",
            "It's okay to feel uncomfortable—what's your next step?",
            "What's making you feel like this? Let's explore it.",
            "You don't have to face this alone. I'm here for you.",
            "Even difficult feelings like disgust can lead to insight.",
            "What's the best way to address what's bothering you?",
            "This emotion is valid—let's process it together.",
            "What's one thing that might help you feel better right now?",
            "Let's focus on what's in your control to ease this feeling.",
            "I'm here to help you work through this moment.",
            "What's the situation that's making you feel this way?",
            "It's okay to take time to figure this out.",
            "Sometimes naming the cause can make it feel smaller.",
            "Let's explore how we can address this feeling.",
            "What's one step toward feeling better about this?",
            "You're not alone—I'm here to help.",
        ],
        "Indecisive": [
            "It's okay to feel uncertain. Want to talk through your options?",
            "What's making the decision hard? Let's figure it out.",
            "Sometimes taking a step back can help. What's your gut saying?",
            "You don't have to rush. Let's explore your choices.",
            "What's the first thing that comes to mind? Let's start there.",
            "It's okay to feel unsure—what's the main concern?",
            "Want to list the pros and cons together?",
            "You've got this. Let's take it one step at a time.",
            "What's holding you back from deciding? Let's unpack it.",
            "Sometimes clarity comes with time. What's the rush?",
            "What's the best-case scenario for each option?",
            "It's okay to not have all the answers right now.",
            "What feels most aligned with your values?",
            "Sometimes it helps to talk it out. Want to share more?",
            "What's the worst-case scenario? Let's face it together.",
            "Let's simplify the choices—what feels most right?",
            "You're capable of making a great choice—trust yourself.",
            "What's one small step you can take toward clarity?",
            "It's okay to make a decision and adjust later.",
            "You're not alone—want to brainstorm together?",
            "What's the decision you'd make if fear wasn't a factor?",
            "Trust your instincts—they're often right.",
            "What's the first step toward deciding?",
            "You've faced tough choices before—you can handle this.",
            "What's the outcome you're hoping for?",
            "Let's take a moment to reflect and breathe.",
            "What's one thing you're certain about in this situation?",
            "You're more decisive than you think. Let's prove it.",
            "What feels like the smallest step forward?",
            "No decision is permanent. Take the leap.",
        ],
        "Depressed": [
            "I'm so sorry you're feeling this way. I'm here for you.",
            "You don't have to face this alone. Let's talk about it.",
            "Your feelings are valid—what's on your mind?",
            "Even the darkest times pass. Let's work through this together.",
            "Take a deep breath. You're not alone in this.",
            "You're stronger than you think, even if it doesn't feel like it.",
            "Would it help to share what's been weighing on you?",
            "I care about you, and I'm here to listen.",
            "Let's take things one step at a time. You've got this.",
            "Your emotions are important—how can I support you?",
            "Sometimes small steps lead to big changes. What's one thing you can do today?",
            "It's okay to feel low. Let's focus on ways to lift your spirits.",
            "Would you like to talk about what's been causing these feelings?",
            "Remember, you've faced hard times before and come through them.",
            "I believe in you. Let's navigate this together.",
            "Even when it feels hopeless, there's always a way forward.",
            "Let's focus on small wins today. What's one thing you can do for yourself?",
            "It's okay to ask for help—you don't have to do this alone.",
            "Your feelings matter. Let's explore them at your pace.",
            "Take it one moment at a time. You're doing your best.",
            "You're not a burden, and you're not alone.",
            "What's something that has brought you peace in the past?",
            "Even on hard days, you're still valuable and worthy.",
            "Would it help to try a calming exercise or distraction?",
            "Let's focus on what's within your control right now.",
            "You're doing better than you think. I'm proud of you.",
            "It's okay to rest and take care of yourself.",
            "What's one small thing you're grateful for today?",
            "You're stronger than you feel. Let's find the next step together.",
            "I'm here, and I'm not going anywhere. Let's face this together.",
        ],
        "Confused": [
            "It's okay to feel uncertain. What's on your mind?",
            "What's making you feel confused? Let's figure it out together.",
            "Sometimes confusion is a sign of growth. Let's unpack it.",
            "You don't have to figure this out alone. I'm here to help.",
            "What's the main thing that's unclear for you right now?",
            "It's okay to take your time to sort through things.",
            "Let's break this down into smaller parts.",
            "What's the first question or concern you have?",
            "Even confusion has its place—it means you're thinking critically.",
            "What's one thing you're certain about in this situation?",
            "Let's focus on what's within your control right now.",
            "Would talking it out help bring some clarity?",
            "Confusion can feel overwhelming, but we'll get through it.",
            "What's the biggest question you're wrestling with?",
            "Take a deep breath—it's okay to not have all the answers.",
            "Sometimes writing things down can help. Want to try?",
            "What's one small step toward understanding this better?",
            "You're not alone in feeling this way. Let's work through it.",
            "What's the source of your confusion? Let's explore it.",
            "Even when things feel unclear, you're doing your best.",
            "What's one thing that might bring you clarity?",
            "Let's focus on the facts. What do you know for sure?",
            "Confusion often leads to insight. Let's take it step by step.",
            "You've handled confusing situations before—you'll get through this too.",
            "It's okay to ask questions or take time to understand.",
            "What's one thing you'd like to focus on right now?",
            "Let's narrow it down—what's the most important thing here?",
            "Sometimes clarity comes with time. Be patient with yourself.",
            "What's the biggest challenge you're facing in understanding this?",
            "You've got this. Let's make sense of it together.",
        ],
        "Anxious": [
            "I'm here to support you. What's making you feel this way?",
            "Take a deep breath. You're safe here.",
            "Anxiety can be overwhelming, but you've faced it before.",
            "Let's break this down—what's the biggest concern right now?",
            "Would it help to talk through what's on your mind?",
            "It's okay to feel anxious. Let's work through it together.",
            "What's one small thing you can control in this moment?",
            "Your feelings are valid. How can I help you feel more at ease?",
            "Sometimes grounding exercises can help. Want to try one?",
            "Let's take it one step at a time. You're not alone.",
            "What's something comforting you can focus on right now?",
            "You're doing your best, and that's enough.",
            "Would it help to list out your worries together?",
            "It's okay to not have all the answers right now.",
            "Let's focus on the present moment. What's one thing you can see, hear, or feel?",
            "Anxiety often exaggerates fears. Let's look at this logically.",
            "You're safe, even if it doesn't feel that way.",
            "What's the worst-case scenario, and how could we handle it?",
            "Take a moment to breathe deeply. You've got this.",
            "I'm here to listen. Share as much or as little as you want.",
            "What's one thing you can do to feel more grounded?",
            "Let's focus on what's real and manageable right now.",
            "You've overcome anxious moments before—you can do it again.",
            "What's one thing that's helped calm you in the past?",
            "It's okay to pause and take a moment for yourself.",
            "You don't have to face this alone. I'm here for you.",
            "What's the smallest step you can take toward feeling better?",
            "Your thoughts don't define you. Let's focus on reality.",
            "Would it help to write down your worries and revisit them later?",
            "Even in anxiety, you're still strong. Let's take this moment by moment.",
        ],
        "Default": [
            "It's okay to feel the way that you're feeling right now. What's on your mind?", 
            "Your feelings matter. Want to talk about them?", 
            "I'm here to support you, how can I help?", 
            "Take a moment to reflect, how are you truly feeling?", 
            "Your emotions are valid. Let's unpack them together.",
            "Sometimes we can feel multiple things at once—what's standing out?",
            "You might be processing a lot—how can I assist?",
            "Let's focus on one thing at a time. What's bothering you?",
            "It's normal to feel unsure sometimes. I'm here to help.",
            "Try to name what you're feeling—it might help.",
            "Take a moment to breathe and gather your thoughts.",
            "Self-reflection is powerful. What's been on your mind?",
            "Would you like to share more? I'm here to listen.",
            "Emotions are signals—what do you think yours are telling you?",
            "It's okay to take your time figuring out how you feel.",
            "How about we explore what's causing this feeling?",
            "I'm here to guide you through this moment.",
            "Sometimes it's hard to put feelings into words—that's okay.",
            "Let's approach this step by step. What's the first thing on your mind?",
            "You're not alone—let's work through this together.",
            "It's okay to feel a little lost sometimes—how can I help?",
            "You don't need to have it all figured out—what's one thing we can focus on?",
            "Emotions can be tricky—what do you think yours are pointing to?",
            "Would you like some tips on managing your current mood?",
            "Whatever you're feeling, it's valid. Let's talk about it.",
            "How can I make this moment better for you?",
            "Feel free to share whatever's on your mind—no judgment here.",
            "Would you like to try a mindfulness exercise?",
            "Sometimes journaling or talking can help—want to try that?",
            "I'm here for you. Let's navigate your feelings together.",
        ],
    }

    # Function to respond to user input
    def respond():
        user_input = bot_input.get().strip()
        if not user_input:
            messagebox.showwarning("Empty Input", "Please enter how you feel.")
            return

        # Normalize user input
        mood = user_input.capitalize()

        # Get a random response based on mood or default
        response = random.choice(bot_responses.get(mood, bot_responses["Default"]))

        # Append conversation to the chat
        chat_textbox.configure(state="normal")  # Enable textbox for writing
        chat_textbox.insert("end", f"You: {user_input}\n")
        chat_textbox.insert("end", f"Bot: {response}\n\n")
        chat_textbox.configure(state="disabled")  # Disable textbox to make it read-only
        chat_textbox.yview("end")  # Scroll to the end of the chat

        bot_input.delete(0, "end")  # Clear the input field

    # Send button
    send_button = ctk.CTkButton(main_content_frame, text="Send", command=respond, fg_color="#FFC0CB")
    send_button.pack(pady=10)